{% set version = '0.2.8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mockthat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mockthat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mockthat/mockthat_{{ version }}.tar.gz
  sha256: 73cc9e0dfbb1fd893288c317dc90d43c55696b3ae8ef3a2845eeea7bef23470a

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rlang
  run:
    - r-base
    - r-rlang

test:
  commands:
    - $R -e "library('mockthat')"           # [not win]
    - "\"%R%\" -e \"library('mockthat')\""  # [win]

about:
  home: https://nbenn.github.io/mockthat/
  license: MIT
  summary: With the deprecation of mocking capabilities shipped with 'testthat' as of 'edition
    3' it is left to third-party packages to replace this functionality, which in some
    test-scenarios is essential in order to run unit tests in limited environments (such
    as no Internet connection). Mocking in this setting means temporarily substituting
    a function with a stub that acts in some sense like the original function (for example
    by serving a HTTP response that has been cached as a file). The only exported function
    'with_mock()' is modeled after the eponymous 'testthat' function with the intention
    of providing a drop-in replacement.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - mlondschien
    - conda-forge/r

# Package: mockthat
# Title: Function Mocking for Unit Testing
# Version: 0.2.8
# Authors@R: person(given = "Nicolas", family = "Bennett", role = c("aut", "cre"), email = "nicolas.bennett@stat.math.ethz.ch")
# Description: With the deprecation of mocking capabilities shipped with 'testthat' as of 'edition 3' it is left to third-party packages to replace this functionality, which in some test-scenarios is essential in order to run unit tests in limited environments (such as no Internet connection). Mocking in this setting means temporarily substituting a function with a stub that acts in some sense like the original function (for example by serving a HTTP response that has been cached as a file). The only exported function 'with_mock()' is modeled after the eponymous 'testthat' function with the intention of providing a drop-in replacement.
# License: MIT + file LICENSE
# URL: https://nbenn.github.io/mockthat/
# BugReports: https://github.com/nbenn/mockthat/issues
# Depends: R (>= 3.3.0)
# Imports: utils, rlang
# Suggests: testthat, pkgload, curl, jsonlite, withr
# Encoding: UTF-8
# Language: en-US
# RoxygenNote: 7.2.1
# NeedsCompilation: no
# Packaged: 2022-10-31 13:34:03 UTC; nbennett
# Author: Nicolas Bennett [aut, cre]
# Maintainer: Nicolas Bennett <nicolas.bennett@stat.math.ethz.ch>
# Repository: CRAN
# Date/Publication: 2022-11-01 08:07:45 UTC
